#!/bin/bash

javac -cp $HADOOP_INSTALL/share/hadoop/common/hadoop-common-2.2.0.jar:$HADOOP_INSTALL/share/hadoop/mapreduce/hadoop-mapreduce-client-core-2.2.0.jar:$HADOOP_INSTALL/share/hadoop/common/lib/commons-cli-1.2.jar ValuesWritable.java PhoneLogMapReduce.java

echo "Compiled"

jar cvf PhoneLog.jar *.class

echo "Compressed"

rm -r ../output

echo "Directory Removed"

hadoop jar PhoneLog.jar PhoneLogMapReduce ../input/log_sample.txt ../output

echo "----------RESULTS----------"

cat ../output/part*

echo "------------END------------"
